const {chromium}=require('playwright');const fs=require('node:fs');const path=require('node:path');const {pathToFileURL}=require('node:url');
(async()=>{const out=path.join(__dirname,'nahledy');fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1920,height:1080},deviceScaleFactor:1});const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
try{
const scenarios=[['host-overlay','Jan Novák','moderátor','transparent'],['host-svetle','Jan Novák','moderátor','light'],['host-tmave','Jan Novák','moderátor','dark'],['host-dlouhe','Alexandr Černohorský-Novotný','vedoucí organizačního týmu a koordinátor závodu','light'],['host-bez-funkce','Jan Novák','','transparent']];
if(process.env.GUEST_NAME?.trim())scenarios.push(['host-vlastni',process.env.GUEST_NAME,process.env.GUEST_ROLE??'','transparent']);
for(const [file,name,role,background] of scenarios){await page.goto(pathToFileURL(path.join(__dirname,'index.html')).href+'?'+new URLSearchParams({capture:'1',name,role,background}));await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(80);const check=await page.evaluate(()=>({font:document.fonts.check('400 40px Exo')&&document.fonts.check('900 40px Exo'),visible:!document.getElementById('guest').hidden,error:document.getElementById('status').classList.contains('error'),roleHidden:document.getElementById('guest-role').hidden}));checks.push({file,pass:check.font&&check.visible&&!check.error&&check.roleHidden===!role.trim()});await page.screenshot({path:path.join(out,file+'.png'),omitBackground:background==='transparent'});
if(file==='host-overlay'){const box=await page.locator('.guest-card').boundingBox();await page.screenshot({path:path.join(out,'host-detail.png'),clip:{x:box.x-4,y:box.y-72,width:box.width+8,height:box.height+76},omitBackground:true});await page.setViewportSize({width:960,height:540});await page.addStyleTag({content:'body.capture .viewport{width:960px;height:540px}body.capture .stage{transform:scale(.5)!important}'});await page.screenshot({path:path.join(out,'host-polovicni.png'),omitBackground:true});await page.setViewportSize({width:1920,height:1080});}}
await page.goto(pathToFileURL(path.join(__dirname,'index.html')).href);await page.locator('#name').fill('');checks.push({case:'missing-name',pass:await page.locator('#guest').isHidden()});await page.locator('#name').fill('<script>alert(1)</script>');checks.push({case:'safe-text',pass:await page.locator('#guest-name').textContent()==='<script>alert(1)</script>'});await page.locator('#toggle').click();checks.push({case:'hide',pass:await page.locator('#guest').isHidden()});await page.locator('#toggle').click();checks.push({case:'show',pass:await page.locator('#guest').isVisible()});await page.locator('#name').fill('Jan Novák');await page.locator('#role').fill('');await page.locator('#link').click();await page.reload();checks.push({case:'saved-url',pass:await page.locator('#name').inputValue()==='Jan Novák'&&await page.locator('#role').inputValue()===''});
}finally{await browser.close();fs.writeFileSync(path.join(__dirname,'kontrola.json'),JSON.stringify({errors,checks},null,2));}
const failures=checks.filter(c=>!c.pass);console.log(JSON.stringify({card:'host',errors,total:checks.length,failures}));if(errors.length||failures.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
